-- MySQL Script generated by MySQL Workbench
-- Sat Apr 25 15:43:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbm_project_f1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbm_project_f1` ;

-- -----------------------------------------------------
-- Schema dbm_project_f1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbm_project_f1` DEFAULT CHARACTER SET utf8 ;
USE `dbm_project_f1` ;

-- -----------------------------------------------------
-- Table `dbm_project_f1`.`circuits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbm_project_f1`.`circuits` ;

CREATE TABLE IF NOT EXISTS `dbm_project_f1`.`circuits` (
  `circuitId` INT NOT NULL,
  `circuitRef` VARCHAR(15) NULL,
  `name` VARCHAR(45) NULL,
  `location` VARCHAR(25) NULL,
  `country` VARCHAR(12) NULL,
  `lat` DECIMAL(8,4) NULL,
  `lng` DECIMAL(8,4) NULL,
  `alt` INT ZEROFILL NULL,
  `url` VARCHAR(90) NULL,
  PRIMARY KEY (`circuitId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbm_project_f1`.`constructorResults`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbm_project_f1`.`constructorResults` ;

CREATE TABLE IF NOT EXISTS `dbm_project_f1`.`constructorResults` (
  `constructorResultsId` INT NOT NULL,
  `raceId` INT NULL,
  `constructorId` INT NULL,
  `points` INT NULL,
  `status` VARCHAR(1) NULL,
  PRIMARY KEY (`constructorResultsId`),
  INDEX `raceId_idx` (`raceId` ASC) VISIBLE,
  INDEX `constructorId_idx` (`constructorId` ASC) VISIBLE,
  CONSTRAINT `fk_constResults_races_raceId`
    FOREIGN KEY (`raceId`)
    REFERENCES `dbm_project_f1`.`races` (`raceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_constResults_constructors_constructorId`
    FOREIGN KEY (`constructorId`)
    REFERENCES `dbm_project_f1`.`constructors` (`constructorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbm_project_f1`.`constructorStandings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbm_project_f1`.`constructorStandings` ;

CREATE TABLE IF NOT EXISTS `dbm_project_f1`.`constructorStandings` (
  `constructorStandingsId` INT NOT NULL,
  `raceId` INT NULL,
  `constructorId` INT NULL,
  `points` INT NULL,
  `position` INT NULL,
  `positionText` VARCHAR(2) NULL,
  `wins` INT NULL,
  PRIMARY KEY (`constructorStandingsId`),
  INDEX `raceId_idx` (`raceId` ASC) VISIBLE,
  INDEX `constructorId_idx` (`constructorId` ASC) VISIBLE,
  CONSTRAINT `fk_constrStand_races_raceId`
    FOREIGN KEY (`raceId`)
    REFERENCES `dbm_project_f1`.`races` (`raceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_constrStand_constructors_constructorId`
    FOREIGN KEY (`constructorId`)
    REFERENCES `dbm_project_f1`.`constructors` (`constructorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbm_project_f1`.`constructors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbm_project_f1`.`constructors` ;

CREATE TABLE IF NOT EXISTS `dbm_project_f1`.`constructors` (
  `constructorId` INT NOT NULL,
  `constructorRef` VARCHAR(25) NULL,
  `name` VARCHAR(25) NULL,
  `nationality` VARCHAR(20) NULL,
  `url` VARCHAR(90) NULL,
  PRIMARY KEY (`constructorId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbm_project_f1`.`driverStandings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbm_project_f1`.`driverStandings` ;

CREATE TABLE IF NOT EXISTS `dbm_project_f1`.`driverStandings` (
  `driverStandingsId` INT NOT NULL,
  `raceId` INT NULL,
  `driverId` INT NULL,
  `points` INT NULL,
  `position` INT NULL,
  `positionText` VARCHAR(3) NULL,
  `wins` INT NULL,
  PRIMARY KEY (`driverStandingsId`),
  INDEX `raceId_idx` (`raceId` ASC) VISIBLE,
  INDEX `driverId_idx` (`driverId` ASC) VISIBLE,
  CONSTRAINT `fk_driverStand_races_raceId`
    FOREIGN KEY (`raceId`)
    REFERENCES `dbm_project_f1`.`races` (`raceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_driverStand_drivers_driverId`
    FOREIGN KEY (`driverId`)
    REFERENCES `dbm_project_f1`.`drivers` (`driverId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbm_project_f1`.`drivers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbm_project_f1`.`drivers` ;

CREATE TABLE IF NOT EXISTS `dbm_project_f1`.`drivers` (
  `driverId` INT NOT NULL,
  `driverRef` VARCHAR(20) NULL,
  `number` INT NULL,
  `code` VARCHAR(3) NULL,
  `forename` VARCHAR(15) NULL,
  `surname` VARCHAR(20) NULL,
  `dob` DATE NULL,
  `nationality` VARCHAR(20) NULL,
  `url` VARCHAR(90) NULL,
  PRIMARY KEY (`driverId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbm_project_f1`.`lapTimes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbm_project_f1`.`lapTimes` ;

CREATE TABLE IF NOT EXISTS `dbm_project_f1`.`lapTimes` (
  `raceId` INT NOT NULL,
  `driverId` INT NOT NULL,
  `lap` INT NOT NULL,
  `position` INT NULL,
  `time` TIME(3) NULL,
  `milliseconds` INT NULL,
  PRIMARY KEY (`raceId`, `driverId`, `lap`),
  INDEX `driverId_idx` (`driverId` ASC) VISIBLE,
  CONSTRAINT `fk_lapTimes_races_raceId`
    FOREIGN KEY (`raceId`)
    REFERENCES `dbm_project_f1`.`races` (`raceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lapTimes_drivers_driverId`
    FOREIGN KEY (`driverId`)
    REFERENCES `dbm_project_f1`.`drivers` (`driverId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbm_project_f1`.`pitStops`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbm_project_f1`.`pitStops` ;

CREATE TABLE IF NOT EXISTS `dbm_project_f1`.`pitStops` (
  `raceId` INT NOT NULL,
  `driverId` INT NOT NULL,
  `stop` INT NOT NULL,
  `lap` INT NULL,
  `time` TIME(3) NULL,
  `duration` TIME(3) NULL,
  `milliseconds` INT NULL,
  PRIMARY KEY (`raceId`, `driverId`, `stop`),
  INDEX `driverId_idx` (`driverId` ASC) VISIBLE,
  CONSTRAINT `fk_pitStops_races_raceId`
    FOREIGN KEY (`raceId`)
    REFERENCES `dbm_project_f1`.`races` (`raceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pitStops_drivers_driverId`
    FOREIGN KEY (`driverId`)
    REFERENCES `dbm_project_f1`.`drivers` (`driverId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbm_project_f1`.`qualifying`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbm_project_f1`.`qualifying` ;

CREATE TABLE IF NOT EXISTS `dbm_project_f1`.`qualifying` (
  `qualifyId` INT NOT NULL,
  `raceId` INT NULL,
  `driverId` INT NULL,
  `constructorId` INT NULL,
  `number` INT NULL,
  `position` INT NULL,
  `q1` TIME(3) NULL,
  `q2` TIME(3) NULL,
  `q3` TIME(3) NULL,
  PRIMARY KEY (`qualifyId`),
  INDEX `raceId_idx` (`raceId` ASC) VISIBLE,
  INDEX `driverId_idx` (`driverId` ASC) VISIBLE,
  INDEX `constructorId_idx` (`constructorId` ASC) VISIBLE,
  CONSTRAINT `fk_qualifying_races_raceId`
    FOREIGN KEY (`raceId`)
    REFERENCES `dbm_project_f1`.`races` (`raceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qualifying_drivers_driverId`
    FOREIGN KEY (`driverId`)
    REFERENCES `dbm_project_f1`.`drivers` (`driverId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qualifying_constructors_constructorId`
    FOREIGN KEY (`constructorId`)
    REFERENCES `dbm_project_f1`.`constructors` (`constructorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbm_project_f1`.`races`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbm_project_f1`.`races` ;

CREATE TABLE IF NOT EXISTS `dbm_project_f1`.`races` (
  `raceId` INT NOT NULL,
  `year` NVARCHAR(4) NULL,
  `round` INT NULL,
  `circuitId` INT NULL,
  `name` VARCHAR(40) NULL,
  `date` DATE NULL,
  `time` TIME(3) NULL,
  `url` VARCHAR(90) NULL,
  PRIMARY KEY (`raceId`),
  INDEX `circuitId_idx` (`circuitId` ASC) VISIBLE,
  CONSTRAINT `fk_races_circuits_circuitId`
    FOREIGN KEY (`circuitId`)
    REFERENCES `dbm_project_f1`.`circuits` (`circuitId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbm_project_f1`.`results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbm_project_f1`.`results` ;

CREATE TABLE IF NOT EXISTS `dbm_project_f1`.`results` (
  `resultId` INT NOT NULL,
  `raceId` INT NULL,
  `driverId` INT NULL,
  `constructorId` INT NULL,
  `number` INT NULL,
  `grid` INT NULL,
  `position` INT NULL,
  `positionText` VARCHAR(2) NULL,
  `positionOrder` INT NULL,
  `points` INT NULL,
  `laps` INT NULL,
  `time` TIME(3) NULL,
  `milliseconds` INT NULL,
  `fastestLap` INT NULL,
  `rank_race` INT NULL,
  `fastestLapTime` TIME(3) NULL,
  `fastestLapSpeed` INT NULL,
  `statusId` INT NULL,
  PRIMARY KEY (`resultId`),
  INDEX `raceId_idx` (`raceId` ASC) VISIBLE,
  INDEX `driverId_idx` (`driverId` ASC) VISIBLE,
  INDEX `constructorId_idx` (`constructorId` ASC) VISIBLE,
  CONSTRAINT `fk_results_races_raceId`
    FOREIGN KEY (`raceId`)
    REFERENCES `dbm_project_f1`.`races` (`raceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_drivers_driverId`
    FOREIGN KEY (`driverId`)
    REFERENCES `dbm_project_f1`.`drivers` (`driverId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_constructors_constructorId`
    FOREIGN KEY (`constructorId`)
    REFERENCES `dbm_project_f1`.`constructors` (`constructorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
